version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://localhost:3001
    volumes:
      - ./client:/usr/app
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/stories
      - PORT=3001
      - JWT_SECRET=password
    volumes:
      - ./server:/usr/app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}